// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TranslateBot.Data;

namespace TranslateBot.Migrations
{
    [DbContext(typeof(LocalDbContext))]
    [Migration("20191016154739_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.11-servicing-32099");

            modelBuilder.Entity("TranslateBot.Models.Phrase", b =>
                {
                    b.Property<int>("PhraseId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("dst");

                    b.Property<string>("src");

                    b.HasKey("PhraseId");

                    b.ToTable("Phrases");
                });
#pragma warning restore 612, 618
        }
    }
}
